name: Package

on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-22.04
    name: Package
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt install build-essential gcc-arm-none-eabi
          arm-none-eabi-g++ --version

      - name: Build firmware
        run: make all
