name: Package

on: push

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    container: fedora:38
    steps:
      - name: Install dependencies
        run: |
          sudo dnf update
          sudo dnf install git nodejs arm-none-eabi-binutils-cs arm-none-eabi-gcc-cs arm-none-eabi-gcc-cs-c++ arm-none-eabi-newlib ninja-build cmake
          arm-none-eabi-g++ --version

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Build firmware
        run: |
          cmake --preset arm-gnu
          cmake --build --preset release

      - name: Make firmware archive
        run: |
          mkdir firmware
          cp build/src/kyma/Release/kyma.bin firmware
          cp build/src/hades/Release/hades.bin firmware
          cp build/src/astra/Release/astra.bin firmware

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: firmware
          if-no-files-found: error

  release:
    name: Release
    needs: package
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Get Artifacts
        uses: actions/download-artifact@v3

      - name: Show artifacts
        run: ls -la

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            ./LICENSE.txt
            ./firmware/**
