name: Package

on:
  workflow_dispatch: # lets you run a build from the UI
  push:

jobs:
  package:
    name: Package
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt install build-essential gcc-arm-none-eabi
          arm-none-eabi-g++ --version

      - name: Build firmware
        run: make all

      - name: Make firmware archive
        run: |
          mkdir firmware
          cp src/Template/build/Template.bin firmware

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: firmware
          if-no-files-found: error

  release:
    name: Release
    needs: package
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Get Artifacts
        uses: actions/download-artifact@v3

      - name: Show artifacts
        run: ls -la

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ./LICENSE.txt
            ./firmware/**
