name: Package

on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-22.04
    name: Package
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt install build-essential gcc-arm-none-eabi
          arm-none-eabi-g++ --version

      - name: Build firmware
        run: make all

      - name: Zip firmware
        run: |
          mkdir firmware
          cp src/Template/build/Template.bin firmware
          7z a -tzip firmware.zip firmware

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: firmware.zip
          path: firmware.zip

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          # download-artifact puts these files in their own dirs...
          # Using globs sidesteps having to pass the version around
          files: |
            */firmware.zip
