name: Pre Commit Hooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Check Pre-Commit Hooks
        run: pre-commit run --all-files
